### ISSUE TITLE
Question: why don't get rid of cookies on a cachable response

### ISSUE THREAD

**Issue by sithmel** [tes/reliable-get#13]
In this test I check if I preserve the cookies in a response:
https://github.com/tes/reliable-get/blob/async-deco/tests/reliable-get.test.js#L333
But the response is cachable, can we just get rid of the cookies for cachable responses ?

**Comment by cliftonc** [comment]
Yes, we never want to cache set cookies, so best to be consistent.

**Comment by sithmel** [comment]
ok, I'll amend the test
