### ISSUE TITLE
Serve cached / stale content on 404

### ISSUE THREAD

**Issue by cliftonc** [tes/reliable-get#20]
At the moment, if we get any response except a 200 we treat it as an error and return the stale content.

https://github.com/tes/reliable-get/blob/master/lib/getRequest.js#L55

This then triggers the error handler, which winds its way down to here:

https://github.com/tes/compoxure/blob/master/src/middleware/proxy.js#L122

Which is driven by config (e.g. for `app-resource`): https://github.com/tes/service-page-composer/blob/master/config/live.json#L461

This means that if we delete a resource, and `app-resource` starts responding with a 404, then it will serve the stale / cached content.

I suspect we should only do this for 5xx and just always send through 4xx without serving stale ?  

@sithmel @bettiolo

**Comment by sithmel** [comment]
It makes sense only fire an error for status >= 500.
Does it still make sense log every 302 (INFO) or 404 (warn) ? Should we consider them "ok" instead ?

**Comment by sithmel** [comment]
It might be a good idea make this a configuration detail

**Comment by bettiolo** [comment]
Just follow the error definition of the RFC: https://tools.ietf.org/html/rfc5861

**Comment by sithmel** [comment]
@bettiolo makes sense. I'll implement it in that way

**Comment by sithmel** [comment]
After a first implementation I have decided to preserve the current behaviour:
it is still returning an error on 4XX and 3XX.

The difference is that these cases don't trigger the fallback mechanism anymore

**Comment by bettiolo** [comment]
What do you mean by "still returning an error" ?

**Comment by sithmel** [comment]
reliable-get returns an error if a backend service returns status code !== 200
The error carries out all the information (statusCode for example) and compoxure behaves accordingly.
