### ISSUE TITLE
Surrogate Keys

### ISSUE THREAD

**Issue by cliftonc** [tes/reliable-get#22]
We really need the ability to add a surrogate key to an element, to enable flushing a batch of keys in the cache.

Use case:  `{{country}}:resource:{{id}}:{{experiment}}`

The above cache key will give you an item per country and running experiment / variant for any resource page.  When someone edits a resource we want to flush the cache for all the variants.

At the moment we iterate over all possible countries and generate the possible key sets, then try and flush individually.

If we allowed the addition of a surrogate key - in this case `resource:{{id}}` - then we could send a command to flush by that, which would then delete all the associated keys.

This is an incredibly useful feature. 

The cache-manager we use doesn't support this, so we have two options:

1.  Change it there and submit a PR, plus change it in the storage libraries (?) for cache-manager.
2.  Remove cache-manager and just use our old redis client, and add it there.

I prefer 2 - but would appreciate your thoughts @sithmel.

/cc @bettiolo

**Comment by bettiolo** [comment]
I feel that the cache-manager with different backends is not keeping it simple for our user case.

**Comment by sithmel** [comment]
I am already working on a different implementation of memoize-cache that uses redis directly.
We can add the feature to that object.
The idea is having multiple implementation of memoize-cache with different features.

**Comment by sithmel** [comment]
works in progress: https://github.com/sithmel/memoize-cache/tree/redis-object

**Comment by sithmel** [comment]
still wip, but getting there: https://github.com/sithmel/memoize-cache-redis

**Comment by sithmel** [comment]
done and released
