### ISSUE TITLE
Using information fields added by reliable-get decorator, e.g. cached

### ISSUE THREAD

**Issue by VladDubrovskis** [tes/reliable-get#23]
We are using your library in our application and we take the information about the timing (`realTiming`) that you provide in order to get some metrics about our API response times.

Now, the small issue that we have noticed is that if the response is cached, the response time (`realTiming`) is obviously very short, that is skewing our data about our API response time.

The workaround is pretty easy, we just use the "cached" flag to check if response came from cache, and based on it we record/do not record the custom metric.

My question was, would it be useful to document the additional fields added by decorator (https://github.com/tes/reliable-get/blob/master/index.js#L118) e.g. `realTiming`, `cached`, etc?

Happy to do a PR for it just though will ask first to see if you plan to keep those? E.g. it is undocumented feature which means can probably get removed

**Comment by VladDubrovskis** [comment]
Also just realised there is a test case missing for the fields, happy to add those too as part of one PR

**Comment by gabceb** [comment]
Thanks @VladDubrovskis. We wil be more than happy to take the PRs

**Comment by VladDubrovskis** [comment]
@gabceb Opened a PR: https://github.com/tes/reliable-get/pull/24
