### ISSUE TITLE
Release version without hiredis

### ISSUE THREAD

**Issue by avengerpenguin** [tes/reliable-get#3]
We're having problems with hiredis, but I note that you've removed that dependency altogether on master. Any chance I can convince you to do a release without that dependency in the package.json if it's not needed? :-)

**Comment by cliftonc** [comment]
Yep, will do it later this evening - apologies, I thought I had!

**Comment by gabceb** [comment]
Done via https://github.com/tes/reliable-get/commit/f9149866cc9db9af4d63cabdfed421905c640b03 and published on npm

**Comment by cliftonc** [comment]
Thanks @gabceb

**Comment by avengerpenguin** [comment]
Thanks everyone!
